/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminLeadAndClientIndexRouteImport } from './routes/admin/lead-and-client/index'
import { Route as AdminLeadAndClientCompanyIdIndexRouteImport } from './routes/admin/lead-and-client/$companyId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeadAndClientIndexRoute = AdminLeadAndClientIndexRouteImport.update({
  id: '/lead-and-client/',
  path: '/lead-and-client/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeadAndClientCompanyIdIndexRoute =
  AdminLeadAndClientCompanyIdIndexRouteImport.update({
    id: '/lead-and-client/$companyId/',
    path: '/lead-and-client/$companyId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/lead-and-client/': typeof AdminLeadAndClientIndexRoute
  '/admin/lead-and-client/$companyId/': typeof AdminLeadAndClientCompanyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/lead-and-client': typeof AdminLeadAndClientIndexRoute
  '/admin/lead-and-client/$companyId': typeof AdminLeadAndClientCompanyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/lead-and-client/': typeof AdminLeadAndClientIndexRoute
  '/admin/lead-and-client/$companyId/': typeof AdminLeadAndClientCompanyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login/'
    | '/admin/dashboard/'
    | '/admin/lead-and-client/'
    | '/admin/lead-and-client/$companyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/dashboard'
    | '/admin/lead-and-client'
    | '/admin/lead-and-client/$companyId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login/'
    | '/admin/dashboard/'
    | '/admin/lead-and-client/'
    | '/admin/lead-and-client/$companyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lead-and-client/': {
      id: '/admin/lead-and-client/'
      path: '/lead-and-client'
      fullPath: '/admin/lead-and-client/'
      preLoaderRoute: typeof AdminLeadAndClientIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lead-and-client/$companyId/': {
      id: '/admin/lead-and-client/$companyId/'
      path: '/lead-and-client/$companyId'
      fullPath: '/admin/lead-and-client/$companyId/'
      preLoaderRoute: typeof AdminLeadAndClientCompanyIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminLeadAndClientIndexRoute: typeof AdminLeadAndClientIndexRoute
  AdminLeadAndClientCompanyIdIndexRoute: typeof AdminLeadAndClientCompanyIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminLeadAndClientIndexRoute: AdminLeadAndClientIndexRoute,
  AdminLeadAndClientCompanyIdIndexRoute: AdminLeadAndClientCompanyIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
